# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='USER_FIRST_NAME',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='person',
            name='USER_ID_ERPICPNA',
            field=models.IntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='person',
            name='USER_LAST_NAME',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='person',
            name='USER_URL_IMG_LINK',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name=''),
        ),
    ]
