# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160407_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='USER_ID_ERPICPNA',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
