# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160407_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='USER_FIRST_NAME',
            field=models.CharField(blank=True, help_text='USER_FIRST_NAME', max_length=256, null=True, verbose_name='USER_FIRST_NAME'),
        ),
        migrations.AlterField(
            model_name='person',
            name='USER_LAST_NAME',
            field=models.CharField(blank=True, help_text='USER_LAST_NAME', max_length=256, null=True, verbose_name='USER_LAST_NAME'),
        ),
        migrations.AlterField(
            model_name='person',
            name='USER_URL_IMG_LINK',
            field=models.CharField(blank=True, help_text='USER_URL_IMG_LINK', max_length=256, null=True, verbose_name='USER_URL_IMG_LINK'),
        ),
    ]
