# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160422_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='USER_PERMISSIONS',
            field=models.TextField(blank=True, help_text='USER_PERMISSIONS', null=True, verbose_name='USER_PERMISSIONS'),
        ),
    ]
